name: daypix
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0-285.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^0.8.7+5
  firebase_core: ^2.13.0
  kpostal: ^0.5.1
  remedi_kopo: ^0.0.2
  cloud_firestore: ^4.7.1
  firebase_auth: ^4.6.1
  firebase_storage: ^11.2.1
  provider: ^6.0.5
  intl: ^0.17.0
  google_sign_in: ^6.1.2
  google_maps_flutter: ^2.2.8
  lottie: ^2.4.0
  table_calendar: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/emoji/
  #   - images/a_dot_ham.jpeg
