// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUHSeTeOWyPh8jwVEJ2qPMxgTw5qqI5FE',
    appId: '1:916323534675:web:87cb885aa23c14217dc3a6',
    messagingSenderId: '916323534675',
    projectId: 'daypix-d89f3',
    authDomain: 'daypix-d89f3.firebaseapp.com',
    storageBucket: 'daypix-d89f3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClvx1Wk98yJOKMD4dKonQIfH6ShOoJZHA',
    appId: '1:916323534675:android:239e21e10a6ae0427dc3a6',
    messagingSenderId: '916323534675',
    projectId: 'daypix-d89f3',
    storageBucket: 'daypix-d89f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdXiQybd3dyyEjOL3jWMMSwctV9EoZNt0',
    appId: '1:916323534675:ios:a722aec1f62d886e7dc3a6',
    messagingSenderId: '916323534675',
    projectId: 'daypix-d89f3',
    storageBucket: 'daypix-d89f3.appspot.com',
    iosClientId: '916323534675-rg6ft2n61qoi0jhssfvru7bkfaica8oj.apps.googleusercontent.com',
    iosBundleId: 'com.example.daysSnap',
  );
}
